### ISSUE TITLE
Init Webmin repository

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-webmin#1]
**What type of your feature request?**  

- [ ] ansible
- [ ] readme
- [x] #3

refer to: PRD.md

**Comment by qiaofeng1227** [comment]
1、下载相应的软件包
   到http://www.webmin.com/download.html网站找最新版本，目前的最新版本为1.560，找到下载地址
   wget http://ncu.dl.sourceforge.net/project/webadmin/webmin/1.560/webmin-1.560-1.noarch.rpm
2、安装软件
   rpm -ivh webmin-1.560-1.noarch.rpm
3、登录webmin
   http://localhost:10000本地登录或使用http://ip:10000访问,
   用户名：root

**Comment by geraintlyu** [comment]
#### aliyun-centos7.9
````
"end_check_versions.stdout_lines": [
        "nginx version: nginx/1.20.1", 
        "webmin version: 1.979", 
        "System version: CentOS 7.9", 
        "Image name: webminfangyutest-CentOS7.9"
    ]
````

**Comment by hnczhjh** [comment]
#### webmin on ali on centos7.9       
        "Docker version 20.10.7, build f0df350", 
        "Docker version 20.10.7, build f0df350", 
        "httpd  Server version: Apache/2.4.46 (IUS)", 
        "webmin version: 1.979", 
        "System version: CentOS 7.9", 
        "Image name: webmin-jh-CentOS7.9"
